MULTIPLE_OFFER = 'multiple_offer'
OUTRO = 'outro'
SINGLE_OFFER = 'single_offer'
TRAVEL_DURATION = 'travel_duration'
TRAVEL_INTRO = 'travel_intro'
TRAVEL_LOCATION = 'travel_location'
TRAVEL_TYPE = 'travel_type'